name: production

# on :
#   push:
#     branches:
#       - master   
on:
  pull_request:
    types: [closed]
    branches:
      - "release/*"

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup JDK 14
      uses: actions/setup-java@v2
      with:
        java-version: '14'
        distribution: 'adopt'

    - name: Create Pull Request to Develop
      if: steps.fastlane_release.outcome == 'success' || steps.fastlane_hotfix.outcome == 'success'
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "develop"
        github_token: GITHUB_TOKEN

